import type { SecuritySectorInfo, SectorRequirement, SecuritySector } from "./types"

// Comprehensive Security Sector Definitions
// Each sector represents a Nigerian security agency with unique protocols, challenges, and requirements

export const securitySectors: SecuritySectorInfo[] = [
  {
    id: "npf",
    name: "Nigerian Police Force",
    shortName: "NPF",
    description: "Primary law enforcement agency responsible for internal security, law and order, and crime prevention across Nigeria.",
    jurisdiction: "Nationwide - All 36 states and FCT",
    primaryFocus: [
      "Crime prevention and detection",
      "Public order maintenance",
      "Traffic control and road safety",
      "Protection of lives and property",
      "Criminal investigation",
    ],
    securityProtocols: [
      "Suspect identification and tracking",
      "Crime scene surveillance analysis",
      "Crowd monitoring for public events",
      "Vehicle pursuit and tracking",
      "Evidence chain-of-custody documentation",
    ],
    operationalChallenges: [
      "Large geographic coverage with limited resources",
      "Balancing public safety with privacy rights",
      "Inter-agency coordination requirements",
      "Real-time response to emerging incidents",
      "Managing sensitive witness identification data",
    ],
    integrationPoints: [
      "Criminal records database (AFIS)",
      "Vehicle registration system",
      "Emergency response dispatch (112)",
      "Court evidence management systems",
      "Inter-agency intelligence sharing",
    ],
    color: "#1e40af",
    icon: "Shield",
  },
  {
    id: "nis",
    name: "Nigeria Immigration Service",
    shortName: "NIS",
    description: "Manages border security, immigration control, and issuance of travel documents to regulate entry and exit of persons.",
    jurisdiction: "All ports of entry - Land borders, Airports, Seaports",
    primaryFocus: [
      "Border surveillance and control",
      "Passport and visa issuance",
      "Immigration law enforcement",
      "Detection of illegal immigrants",
      "Human trafficking prevention",
    ],
    securityProtocols: [
      "Passport and document verification",
      "Biometric identity matching at borders",
      "Watchlist screening for wanted persons",
      "Border crossing pattern analysis",
      "Visa overstay detection and tracking",
    ],
    operationalChallenges: [
      "Porous border regions with limited infrastructure",
      "High volume of travelers at major airports",
      "Document fraud and identity spoofing",
      "Coordinating with international agencies",
      "Managing refugee and asylum seeker flows",
    ],
    integrationPoints: [
      "e-Passport database",
      "INTERPOL watchlists",
      "Airline advance passenger information (API)",
      "ECOWAS free movement protocols",
      "Foreign affairs visa systems",
    ],
    color: "#059669",
    icon: "Plane",
  },
  {
    id: "frsc",
    name: "Federal Road Safety Corps",
    shortName: "FRSC",
    description: "Responsible for road safety administration, traffic management, and reducing road accidents across Nigerian highways.",
    jurisdiction: "Federal highways and major road networks",
    primaryFocus: [
      "Traffic monitoring and enforcement",
      "Accident prevention and response",
      "Driver licensing and vehicle inspection",
      "Highway patrol and surveillance",
      "Road safety public education",
    ],
    securityProtocols: [
      "License plate recognition and validation",
      "Speed monitoring and enforcement",
      "Accident scene documentation",
      "Fleet vehicle tracking for commercial transport",
      "Driver behavior analysis",
    ],
    operationalChallenges: [
      "Vast highway network coverage",
      "High fatality rates requiring rapid response",
      "Counterfeit license detection",
      "Coordination with state traffic agencies",
      "Real-time traffic flow management",
    ],
    integrationPoints: [
      "National vehicle identification system (NVIS)",
      "Driver's license database",
      "Insurance verification systems",
      "Emergency medical services dispatch",
      "Road infrastructure monitoring",
    ],
    color: "#d97706",
    icon: "Car",
  },
  {
    id: "nscdc",
    name: "Nigeria Security and Civil Defence Corps",
    shortName: "NSCDC",
    description: "Provides protection for critical national infrastructure, disaster management, and civil defence operations.",
    jurisdiction: "Critical infrastructure sites nationwide",
    primaryFocus: [
      "Critical infrastructure protection",
      "Pipeline and utility surveillance",
      "Disaster response coordination",
      "Private security regulation",
      "Crisis management operations",
    ],
    securityProtocols: [
      "Perimeter intrusion detection",
      "Oil and gas facility monitoring",
      "Sabotage attempt identification",
      "Environmental hazard detection",
      "Mass gathering security assessment",
    ],
    operationalChallenges: [
      "Protecting vast pipeline networks",
      "Vandalism and theft prevention",
      "Coordinating multi-agency disaster response",
      "Monitoring remote infrastructure sites",
      "Balancing accessibility with security",
    ],
    integrationPoints: [
      "NNPC pipeline monitoring systems",
      "Power grid surveillance",
      "NEMA disaster response network",
      "Private security company databases",
      "Environmental monitoring sensors",
    ],
    color: "#7c3aed",
    icon: "Building2",
  },
  {
    id: "customs",
    name: "Nigeria Customs Service",
    shortName: "NCS",
    description: "Manages customs and excise duties, prevents smuggling, and facilitates legitimate trade across Nigerian borders.",
    jurisdiction: "All ports, border crossings, and free trade zones",
    primaryFocus: [
      "Revenue collection and duty assessment",
      "Anti-smuggling operations",
      "Trade facilitation",
      "Prohibited goods interdiction",
      "Cargo inspection and clearance",
    ],
    securityProtocols: [
      "Container and cargo scanning",
      "Document and manifest verification",
      "Prohibited items detection",
      "Trade pattern anomaly analysis",
      "Bonded warehouse surveillance",
    ],
    operationalChallenges: [
      "High volume of cargo throughput",
      "Concealed contraband detection",
      "Corruption and collusion risks",
      "Balancing security with trade efficiency",
      "Cross-border smuggling networks",
    ],
    integrationPoints: [
      "ASYCUDA trade management system",
      "Pre-arrival cargo declarations",
      "Single window trade portal",
      "International customs networks (WCO)",
      "Port authority systems",
    ],
    color: "#0891b2",
    icon: "Package",
  },
  {
    id: "efcc",
    name: "Economic and Financial Crimes Commission",
    shortName: "EFCC",
    description: "Investigates and prosecutes financial crimes including fraud, money laundering, and economic sabotage.",
    jurisdiction: "Nationwide financial crime investigation",
    primaryFocus: [
      "Financial fraud investigation",
      "Money laundering detection",
      "Cybercrime investigation",
      "Asset recovery operations",
      "Corruption prosecution",
    ],
    securityProtocols: [
      "Suspect movement tracking",
      "Asset location surveillance",
      "Digital forensics evidence capture",
      "Witness protection monitoring",
      "Coordinated raid documentation",
    ],
    operationalChallenges: [
      "Sophisticated criminal networks",
      "Cross-border financial flows",
      "Digital evidence preservation",
      "Protecting whistleblowers and witnesses",
      "High-profile case security",
    ],
    integrationPoints: [
      "Bank verification number (BVN) system",
      "Financial intelligence unit (NFIU)",
      "International asset recovery networks",
      "Court case management systems",
      "Cryptocurrency tracking services",
    ],
    color: "#dc2626",
    icon: "Scale",
  },
  {
    id: "dss",
    name: "Department of State Services",
    shortName: "DSS",
    description: "Intelligence agency responsible for internal security intelligence, counter-terrorism, and protection of key government officials.",
    jurisdiction: "Classified - National security operations",
    primaryFocus: [
      "Counter-terrorism intelligence",
      "VIP protection operations",
      "Internal security threats",
      "Counter-espionage activities",
      "Critical event security",
    ],
    securityProtocols: [
      "Threat actor identification",
      "Secure facility surveillance",
      "Protective intelligence gathering",
      "Counter-surveillance detection",
      "Classified information protection",
    ],
    operationalChallenges: [
      "Evolving terrorist tactics",
      "Insider threat detection",
      "Protecting classified operations",
      "Coordinating with international intelligence",
      "Balancing secrecy with oversight",
    ],
    integrationPoints: [
      "Classified intelligence networks",
      "International partner agencies",
      "Secure communications systems",
      "Threat assessment databases",
      "VIP movement coordination",
    ],
    color: "#374151",
    icon: "Eye",
  },
  {
    id: "correctional",
    name: "Nigerian Correctional Service",
    shortName: "NCoS",
    description: "Manages custodial centers, rehabilitation programs, and non-custodial measures for offenders.",
    jurisdiction: "All federal and state correctional facilities",
    primaryFocus: [
      "Inmate custody and security",
      "Rehabilitation programs",
      "Facility perimeter security",
      "Visitor management",
      "Inmate transfer operations",
    ],
    securityProtocols: [
      "Inmate identification and tracking",
      "Cell block surveillance",
      "Contraband detection",
      "Visitor identity verification",
      "Escape prevention monitoring",
    ],
    operationalChallenges: [
      "Overcrowded facilities",
      "Contraband smuggling prevention",
      "Gang activity monitoring",
      "Inmate violence prevention",
      "Secure transport coordination",
    ],
    integrationPoints: [
      "Criminal justice system records",
      "Court remand databases",
      "Parole and probation tracking",
      "Healthcare management systems",
      "Rehabilitation outcome tracking",
    ],
    color: "#78716c",
    icon: "Lock",
  },
]

// Sector-specific requirements elicited from each agency
export const sectorRequirements: SectorRequirement[] = [
  // Nigerian Police Force Requirements
  {
    id: "req-npf-001",
    sectorId: "npf",
    category: "surveillance",
    priority: "critical",
    requirement: "Real-time facial recognition with configurable privacy masking based on authorization levels",
    rationale: "Enable rapid suspect identification while protecting innocent citizens' privacy rights as mandated by NDPR",
    status: "implemented",
  },
  {
    id: "req-npf-002",
    sectorId: "npf",
    category: "tracking",
    priority: "high",
    requirement: "Cross-camera vehicle tracking with license plate recognition across jurisdictions",
    rationale: "Support vehicle pursuit and stolen vehicle recovery operations across state boundaries",
    status: "implemented",
  },
  {
    id: "req-npf-003",
    sectorId: "npf",
    category: "reporting",
    priority: "high",
    requirement: "Court-admissible evidence export with tamper-proof chain of custody documentation",
    rationale: "Ensure surveillance footage meets judicial standards for criminal prosecution",
    status: "implemented",
  },
  {
    id: "req-npf-004",
    sectorId: "npf",
    category: "interoperability",
    priority: "medium",
    requirement: "Integration with AFIS for automatic fingerprint matching from crime scene footage",
    rationale: "Accelerate suspect identification by linking visual evidence with biometric databases",
    status: "planned",
  },

  // Nigeria Immigration Service Requirements
  {
    id: "req-nis-001",
    sectorId: "nis",
    category: "identification",
    priority: "critical",
    requirement: "Biometric verification at border checkpoints with passport photo matching",
    rationale: "Prevent identity fraud and detect imposters using genuine travel documents",
    status: "implemented",
  },
  {
    id: "req-nis-002",
    sectorId: "nis",
    category: "surveillance",
    priority: "high",
    requirement: "Automated watchlist screening against INTERPOL and national wanted persons databases",
    rationale: "Intercept wanted individuals attempting to enter or exit the country",
    status: "implemented",
  },
  {
    id: "req-nis-003",
    sectorId: "nis",
    category: "tracking",
    priority: "high",
    requirement: "Visa overstay detection with last-known-location tracking for enforcement",
    rationale: "Enforce immigration laws and locate persons who have violated visa conditions",
    status: "in-progress",
  },
  {
    id: "req-nis-004",
    sectorId: "nis",
    category: "compliance",
    priority: "medium",
    requirement: "ECOWAS protocol compliance monitoring for regional free movement verification",
    rationale: "Ensure proper implementation of regional agreements while maintaining security",
    status: "implemented",
  },

  // Federal Road Safety Corps Requirements
  {
    id: "req-frsc-001",
    sectorId: "frsc",
    category: "surveillance",
    priority: "critical",
    requirement: "Highway traffic monitoring with automatic incident detection and alert generation",
    rationale: "Enable rapid response to accidents and reduce highway fatalities",
    status: "implemented",
  },
  {
    id: "req-frsc-002",
    sectorId: "frsc",
    category: "identification",
    priority: "high",
    requirement: "License plate recognition with real-time validation against NVIS database",
    rationale: "Identify unregistered, stolen, or vehicles with expired documentation",
    status: "implemented",
  },
  {
    id: "req-frsc-003",
    sectorId: "frsc",
    category: "tracking",
    priority: "medium",
    requirement: "Commercial fleet tracking with driver behavior analysis for safety compliance",
    rationale: "Monitor dangerous goods transport and enforce driver hour regulations",
    status: "in-progress",
  },
  {
    id: "req-frsc-004",
    sectorId: "frsc",
    category: "reporting",
    priority: "medium",
    requirement: "Automated accident scene documentation with measurement and timeline reconstruction",
    rationale: "Generate accurate accident reports for insurance and legal proceedings",
    status: "planned",
  },

  // Nigeria Security and Civil Defence Corps Requirements
  {
    id: "req-nscdc-001",
    sectorId: "nscdc",
    category: "surveillance",
    priority: "critical",
    requirement: "24/7 critical infrastructure monitoring with tamper and intrusion detection",
    rationale: "Protect oil pipelines, power stations, and other vital national assets",
    status: "implemented",
  },
  {
    id: "req-nscdc-002",
    sectorId: "nscdc",
    category: "tracking",
    priority: "high",
    requirement: "Perimeter breach tracking with automatic responder dispatch integration",
    rationale: "Enable rapid response to sabotage attempts at critical facilities",
    status: "implemented",
  },
  {
    id: "req-nscdc-003",
    sectorId: "nscdc",
    category: "compliance",
    priority: "medium",
    requirement: "Private security company oversight with guard post verification",
    rationale: "Ensure contracted security personnel are performing assigned duties",
    status: "in-progress",
  },

  // Nigeria Customs Service Requirements
  {
    id: "req-customs-001",
    sectorId: "customs",
    category: "surveillance",
    priority: "critical",
    requirement: "Cargo inspection area monitoring with container tracking throughout clearance process",
    rationale: "Prevent cargo tampering and ensure secure handling during inspection",
    status: "implemented",
  },
  {
    id: "req-customs-002",
    sectorId: "customs",
    category: "identification",
    priority: "high",
    requirement: "Prohibited items visual detection using AI-assisted image analysis",
    rationale: "Enhance detection of concealed contraband in scanned cargo images",
    status: "in-progress",
  },
  {
    id: "req-customs-003",
    sectorId: "customs",
    category: "tracking",
    priority: "medium",
    requirement: "Bonded warehouse surveillance with seal integrity verification",
    rationale: "Ensure goods in transit remain secure until duty payment and release",
    status: "implemented",
  },

  // EFCC Requirements
  {
    id: "req-efcc-001",
    sectorId: "efcc",
    category: "surveillance",
    priority: "critical",
    requirement: "Covert surveillance capability with enhanced privacy controls for investigations",
    rationale: "Support undercover financial crime investigations while maintaining legal standards",
    status: "implemented",
  },
  {
    id: "req-efcc-002",
    sectorId: "efcc",
    category: "tracking",
    priority: "high",
    requirement: "Suspect movement pattern analysis with asset location correlation",
    rationale: "Build evidence of financial crime by linking suspect movements to assets",
    status: "implemented",
  },
  {
    id: "req-efcc-003",
    sectorId: "efcc",
    category: "reporting",
    priority: "high",
    requirement: "Forensic-grade video export with metadata preservation for court proceedings",
    rationale: "Ensure evidence integrity for successful prosecution of financial crimes",
    status: "implemented",
  },

  // DSS Requirements
  {
    id: "req-dss-001",
    sectorId: "dss",
    category: "surveillance",
    priority: "critical",
    requirement: "Multi-level access control with compartmentalized surveillance data access",
    rationale: "Protect classified operations while enabling authorized personnel access",
    status: "implemented",
  },
  {
    id: "req-dss-002",
    sectorId: "dss",
    category: "identification",
    priority: "critical",
    requirement: "Threat actor identification with cross-reference to intelligence databases",
    rationale: "Enable rapid identification of known threats at protected locations",
    status: "implemented",
  },
  {
    id: "req-dss-003",
    sectorId: "dss",
    category: "tracking",
    priority: "high",
    requirement: "VIP protection zone monitoring with automatic threat detection",
    rationale: "Ensure security of protected persons through proactive surveillance",
    status: "implemented",
  },

  // Nigerian Correctional Service Requirements
  {
    id: "req-correctional-001",
    sectorId: "correctional",
    category: "surveillance",
    priority: "critical",
    requirement: "Cell block and common area monitoring with behavioral anomaly detection",
    rationale: "Prevent violence, escape attempts, and maintain facility security",
    status: "implemented",
  },
  {
    id: "req-correctional-002",
    sectorId: "correctional",
    category: "identification",
    priority: "high",
    requirement: "Inmate identification verification with location tracking within facilities",
    rationale: "Maintain accurate inmate counts and prevent unauthorized movement",
    status: "implemented",
  },
  {
    id: "req-correctional-003",
    sectorId: "correctional",
    category: "compliance",
    priority: "medium",
    requirement: "Visitor verification and monitoring with contraband detection integration",
    rationale: "Prevent smuggling of prohibited items through visitor areas",
    status: "in-progress",
  },
]

// Helper function to get sector by ID
export function getSectorById(id: SecuritySector): SecuritySectorInfo | undefined {
  return securitySectors.find(s => s.id === id)
}

// Helper function to get requirements by sector
export function getRequirementsBySector(sectorId: SecuritySector): SectorRequirement[] {
  return sectorRequirements.filter(r => r.sectorId === sectorId)
}

// Helper function to get all sectors as options for dropdowns
export function getSectorOptions(): { value: SecuritySector; label: string }[] {
  return securitySectors.map(s => ({ value: s.id, label: s.shortName }))
}
